### ISSUE TITLE
Experiment in real world

### ISSUE THREAD

**Issue by codespring-lh** [mzahana/px4_fast_planner#16]
Hi,I want to do some experiment using Fast-Planner in real world,but I have met some problems.I used Vins-Fusion with D435i and I have modified kino_replan.lauch.But there is no map.
Hoping for your reply.
![2021-04-21 20-43-49 的屏幕截图](https://user-images.githubusercontent.com/63155979/115640705-28a8f180-a34a-11eb-98fc-11106cd18d22.png)
![2021-04-21 20-44-16 的屏幕截图](https://user-images.githubusercontent.com/63155979/115640712-2c3c7880-a34a-11eb-9708-77277195da38.png)
![2021-04-21 20-44-39 的屏幕截图](https://user-images.githubusercontent.com/63155979/115640715-2cd50f00-a34a-11eb-8de1-7153255d314c.png)
![2021-04-21 20-43-04 的屏幕截图](https://user-images.githubusercontent.com/63155979/115640716-2d6da580-a34a-11eb-8763-37e172623bd9.png)

**Comment by codespring-lh** [comment]
And here is my tf_tree.
![2021-04-21 21-24-45屏幕截图](https://user-images.githubusercontent.com/63155979/115645709-6cecbf80-a353-11eb-939a-229d727e17d1.png)

**Comment by atmaca11** [comment]
Hi did you solve the issue ?

**Comment by mzahana** [comment]
Refer to #17
