### ISSUE TITLE
Change camera parameters

### ISSUE THREAD

**Issue by lgh5054** [mzahana/px4_fast_planner#2]
Hello

It's so exciting!

I also want to see the fast-planner 3 days ago and incorporate it into real hardware.

The T265 slam the role of GPS and wants to implement avoidance with the D435

Could you tell me where to change the actual D435 topic, not the simulation?

**Comment by mzahana** [comment]
Hi @lgh5054 

You can change the depth topic using the `depth_topic` argument  in the `px4_fast_planner` [here](https://github.com/mzahana/px4_fast_planner/blob/master/launch/px4_fast_planner.launch#L16)

You also need to specify the camera pose topic using the `camera_pose_topic` argument [here](https://github.com/mzahana/px4_fast_planner/blob/master/launch/px4_fast_planner.launch#L15). This is the camera pose in the `world` frame

There is a node that looks for the transform from the camera frame to the world frame, [see here](https://github.com/mzahana/px4_fast_planner/blob/master/launch/px4_fast_planner.launch#L55-L61)
So, it's required to have transforms
* from `camera_link` to `base_link`. This is already done [here](https://github.com/mzahana/px4_fast_planner/blob/master/launch/px4_fast_planner.launch#L23)
* and from `base_link` to `map`. This is done in the px4 config file [here](https://github.com/mzahana/px4_fast_planner/blob/master/config/px4_config.yaml#L69)
* and from `map` to `world`. This is done [here](https://github.com/mzahana/px4_fast_planner/blob/master/launch/px4_fast_planner.launch#L22)

I hope this helps

**Comment by mzahana** [comment]
Also pay attention to the camera intrinsic parameters, [here](https://github.com/mzahana/px4_fast_planner/blob/master/launch/px4_topo_replan.launch#L33-L36)

**Comment by lgh5054** [comment]
@mzahana Thank you for your answer.

I'll test it and share the results.

**Comment by skyaid** [comment]
@mzahana 
![Screenshot from 2020-06-30 20-14-15](https://user-images.githubusercontent.com/55374072/86120001-7c71f200-bb0e-11ea-9700-b85d4f7600fb.png)

As I said, I changed all parameters, but the screen does not print depth

**Comment by mzahana** [comment]
@skyaid 
No depth will be printed on screen. Instead, you should see point cloud in Rviz. Can you share your tf tree `rosrun rqt_tf_tree rqt_tf_tree` ?

**Comment by skyaid** [comment]
@mzahana 
![frames](https://user-images.githubusercontent.com/55374072/86121016-4170be00-bb10-11ea-82b0-3b5ceb0d81c5.png)

**Comment by mzahana** [comment]
@skyaid You have some issues with your setup.
* Your tree is not well connected
    * It seems that you are not running mavros using launch file that is included in `px4_fast_planner.launch`. It calls `mavros.launch` which uses a custom px4 plugin yaml file. not the default one that comes with mavros
    * The `camera_pose_publisher.py` node is looking for a transformation from `parent_frame` (which is set to `worls` in your file) to `child_frame` (which is set to `camera_link`. However, there is no connection between them! You need to make a connection to the word frame in your tree.
* I think `<arg name="camera_pose_topic" default="/camera_link"/>` is wrong. This should be set to the topic that will be published by the `camera_pose_publisher.py` node which in this file is `camera/pose`

**Comment by skyaid** [comment]
@mzahana Thank you for your prompt reply

There has been a lot of progress

just like you said.

using px4_fast_planner px4.launch and change camera_pose_topic" default="/camera/pose

but tf not found in rviz 
/mavros/local_position/odom 
/mavros/local_position/pose   it's being published

![Screenshot from 2020-07-01 14-21-12](https://user-images.githubusercontent.com/55374072/86206554-a3303700-bba7-11ea-9167-3a204386f427.png)
"/>


![frames](https://user-images.githubusercontent.com/55374072/86206362-2ac97600-bba7-11ea-8d81-1f93d8da630d.png)

**Comment by mzahana** [comment]
@skyaid Please look at the `px4_fast_planner px4.launch` file. You will see that it already includes `geometric_controller.launch`

**Comment by atmaca11** [comment]
@lgh5054 Can you share your e-mail address ?
