### ISSUE TITLE
如何在px4实体上使用呢？期待您的回复！谢谢！

### ISSUE THREAD

**Issue by one-DS** [mzahana/px4_fast_planner#23]

**Comment by ZhangXiaolei314** [comment]
看你是用的t265还是d435i了，如果是d435i，用vins-fusion就行了。之后直接把这个项目部署在板载电脑上就好，但是有一些launch文件中的参数要改改，mavros_controller需要用最新的版本。这个控制器用的px4的rate controller，kv和kp在板载电脑上设置。麻烦你说一下你的具体硬件吧！
