### ISSUE TITLE
Altitude drops

### ISSUE THREAD

**Issue by eldewany** [mzahana/px4_fast_planner#25]
Hello, i successfully setup the simulation environment and every thing runs smoothly, the issue is that after the drone hovers I publish the message at a certain altitude (tried the same of the hovering and different one) and in both cases the drone altitude drops down to 0. What might the problem be ?

**Comment by mzahana** [comment]
@eldewany please share detailed steps.

**Comment by eldewany** [comment]
@mzahana I edited the launch file to change the takeoff altitude, velocity limits and what not. Launch using px4_fast_planner.Launch file, everything starts up, all nodes are running with no errors, rviz is working. I then publish a message on the move_base topic as described using rqt publisher, it starts to drop in altitude but tries to move in the direction specified. Btw I'm on Ubuntu 18.04, melodic, px4 1.11.3

**Comment by one-DS** [comment]
@eldewany  Did you not release altitude Z but only x and y when you released waypoint information?

**Comment by eldewany** [comment]
@one-DS yes i did, here is a screen shot of the console when triggered
![Screenshot from 2021-10-03 16-45-32](https://user-images.githubusercontent.com/52039275/135759133-de95f43a-fa42-43c2-b5ad-b307bf55edce.png)

**Comment by mzahana** [comment]
@eldewany try to publish only one message when you wish to change the goal point, not at a specific rate as you did.
Also, keep in mind that you are constrained by the map size. If you are using the default map size (40m) in x/y axes,  then your goal x position is actually out of bounds, and it won't work as expected.

**Comment by eldewany** [comment]
@mzahana I did as you said, (Changed, x and y to be < 40 ) and published the message once and it still falls, although when it reaches the goal (while crawling on the ground) it takes off again to the specified altitude

**Comment by mzahana** [comment]
I am not sure what's happening in your case. I wil have to re produce the setup. It's been so long since I worked with this software.

**Comment by eldewany** [comment]
@mzahana Thanks for your efforts, waiting for your reply

**Comment by eldewany** [comment]
Fixed by refreshing an installation.
