### ISSUE TITLE
Speed limit for drone motion

### ISSUE THREAD

**Issue by eldewany** [mzahana/px4_fast_planner#26]
Hey, i noticed that the drone is always capped at 1m/s , how can I override that given that I edited the max acceleration and velocity in the launch file.

**Comment by mzahana** [comment]
@eldewany Hi!
Try to pass the [max_vel](https://github.com/mzahana/px4_fast_planner/blob/c3d958e4204af22cd51487492f15ebe6dfef7901/launch/px4_fast_planner.launch#L19) argument into the planners launch files, [here](https://github.com/mzahana/px4_fast_planner/blob/c3d958e4204af22cd51487492f15ebe6dfef7901/launch/px4_fast_planner.launch#L41-L49), and [here](https://github.com/mzahana/px4_fast_planner/blob/c3d958e4204af22cd51487492f15ebe6dfef7901/launch/px4_fast_planner.launch#L51-L59)

**Comment by mzahana** [comment]
@eldewany please close the issue if it is resolved.

**Comment by eldewany** [comment]
@mzahana Yes, thank you fro the support.
