### ISSUE TITLE
can we use this with ardupilot firmware?

### ISSUE THREAD

**Issue by shubham-shahh** [mzahana/px4_fast_planner#29]
Hi, have you tested this repo with ardupilot firmware? I tried to implement it but I face several issues which I posted here [here](https://discuss.ardupilot.org/t/does-the-new-release-of-copter-4-1-0-solve-the-issue-of-attitude-target/77014)

**Comment by mzahana** [comment]
No, I have not. I don't use Ardupilot.

**Comment by shubham-shahh** [comment]
okay thanks
