### ISSUE TITLE
unable to run simulation

### ISSUE THREAD

**Issue by EhrazImam** [mzahana/px4_fast_planner#32]
/px4fp_ws$ roslaunch px4_fast_planner px4_fast_planner.launch

RLException: [px4_fast_planner.launch] is neither a launch file in package [px4_fast_planner] nor is [px4_fast_planner] a launch file name
The traceback for the exception was written to the log file
enord@enord:~/px4fp_ws$

**Comment by mzahana** [comment]
@EhrazImam you will need to setup and source your workspace properly. You will need to have good ROS knowledge before you use this package.

**Comment by EhrazImam** [comment]
Hi @mzahana I am new to ROS can you help me so i can use my depth model in realtime i can calculate depth from CNN but i wanna use it in ros and i am not aware how  can i implement
