### ISSUE TITLE
Change map size to infinity

### ISSUE THREAD

**Issue by lgh5054** [mzahana/px4_fast_planner#6]
Because of the large outdoor space, x=40 y=40 z=5 is small in range. Can I disable this feature?

**Comment by mzahana** [comment]
This is a know limitation. Map size has to be finite. In addition, large map size results in high memory consumption and planning is (so far) not optimized for large map sizes, see this issue https://github.com/HKUST-Aerial-Robotics/Fast-Planner/issues/13.

Also note that planners will not work outside the defined map size

Kindly, report any issues related to Fast-Planner in the [Fast-Planner issues](https://github.com/HKUST-Aerial-Robotics/Fast-Planner/issues)

**Comment by lgh5054** [comment]
@mzahana thanks
