### ISSUE TITLE
kino simulator abnormalities

### ISSUE THREAD

**Issue by lgh5054** [mzahana/px4_fast_planner#7]
The simulator displays strange flight paths. And the drone  flies strangely because of the fast changing route. Please check if it's only on my computer.

**Comment by mzahana** [comment]
Please report any issues related to the planner in (https://github.com/HKUST-Aerial-Robotics/Fast-Planner/issues). This package is just to interface the planner to PX4. In addition, provide enough details to help debugging the problem. It's not clear what you mean by strange paths. The tests work fine on my machine.

**Comment by lgh5054** [comment]
@mzahana  resolved
